# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PetDays' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PetDays
  pod 'Alamofire'
  pod 'SwiftyJSON'

  target 'PetDaysTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PetDaysUITests' do
    # Pods for testing
  end

end
